UD_TEST_PATHS = {
	"Abaza": "UD_data/UD_Abaza-ATB/abq_atb-ud-test.conllu",
	"Abkhaz": "UD_data/UD_Abkhaz-AbNC/ab_abnc-ud-test.conllu",
	"Afrikaans": "UD_data/UD_Afrikaans-AfriBooms/af_afribooms-ud-test.conllu",
    "Akkadian": "UD_data/UD_Akkadian-RIAO/akk_riao-ud-test.conllu",
    "Akuntsu": "UD_data/UD_Akuntsu-TuDeT/aqz_tudet-ud-test.conllu",
	"Albanian": "UD_data/UD_Albanian-STAF/sq_staf-ud-test.conllu",
    "Alemannic": "UD_data/UD_Alemannic-UZH/gsw_uzh-ud-test.conllu",
	"Amharic": "UD_data/UD_Amharic-ATT/am_att-ud-test.conllu",
    "Ancient Greek": "UD_data/UD_Ancient_Greek-PROIEL/grc_proiel-ud-test.conllu",
    "Ancient Hebrew": "UD_data/UD_Ancient_Hebrew-PTNK/hbo_ptnk-ud-test.conllu",
	"Apurina": "UD_data/UD_Apurina-UFPA/apu_ufpa-ud-test.conllu",
	"Arabic": "UD_data/UD_Arabic-PUD/ar_pud-ud-test.conllu",
	"Armenian": "UD_data/UD_Armenian-BSUT/hy_bsut-ud-test.conllu",
	"Assyrian": "UD_data/UD_Assyrian-AS/aii_as-ud-test.conllu",
	"Azerbaijani": "UD_data/UD_Azerbaijani-TueCL/az_tuecl-ud-test.conllu",
	"Bambara": "UD_data/UD_Bambara-CRB/bm_crb-ud-test.conllu",
	"Basque": "UD_data/UD_Basque-BDT/eu_bdt-ud-test.conllu",
	"Bavarian": "UD_data/UD_Bavarian-MaiBaam/bar_maibaam-ud-test.conllu",
	"Beja": "UD_data/UD_Beja-Autogramm/bej_autogramm-ud-test.conllu",
	"Belarusian": "UD_data/UD_Belarusian-HSE/be_hse-ud-test.conllu",
	"Bengali": "UD_data/UD_Bengali-BRU/bn_bru-ud-test.conllu",
	"Bhojpuri": "UD_data/UD_Bhojpuri-BHTB/bho_bhtb-ud-test.conllu",
    "Bokota": "UD_data/UD_Bokota-ChibErgIS/sab_chibergis-ud-test.conllu",
	"Bororo": "UD_data/UD_Bororo-BDT/bor_bdt-ud-test.conllu",
	"Breton": "UD_data/UD_Breton-KEB/br_keb-ud-test.conllu",
	"Bulgarian": "UD_data/UD_Bulgarian-BTB/bg_btb-ud-test.conllu",
	"Buryat": "UD_data/UD_Buryat-BDT/bxr_bdt-ud-test.conllu",
	"Cantonese": "UD_data/UD_Cantonese-HK/yue_hk-ud-test.conllu",
	"Cappadocian": "UD_data/UD_Cappadocian-TueCL/cpg_tuecl-ud-test.conllu",
	"Catalan": "UD_data/UD_Catalan-AnCora/ca_ancora-ud-test.conllu",
	"Cebuano": "UD_data/UD_Cebuano-GJA/ceb_gja-ud-test.conllu",
	"Chinese": "UD_data/UD_Chinese-PUD/zh_pud-ud-test.conllu",
	"Chukchi": "UD_data/UD_Chukchi-HSE/ckt_hse-ud-test.conllu",
	"Classical Armenian": "UD_data/UD_Classical_Armenian-CAVaL/xcl_caval-ud-test.conllu",
	"Classical Chinese": "UD_data/UD_Classical_Chinese-Kyoto/lzh_kyoto-ud-test.conllu",
	"Coptic": "UD_data/UD_Coptic-Scriptorium/cop_scriptorium-ud-test.conllu",
	"Croatian": "UD_data/UD_Croatian-SET/hr_set-ud-test.conllu",
	"Czech": "UD_data/UD_Czech-PDTC/cs_pdtc-ud-test.conllu",
	"Danish": "UD_data/UD_Danish-DDT/da_ddt-ud-test.conllu",
	"Dutch": "UD_data/UD_Dutch-LassySmall/nl_lassysmall-ud-test.conllu",
	"Egyptian": "UD_data/UD_Egyptian-UJaen/egy_ujaen-ud-test.conllu",
	"English": "UD_data/UD_English-GUM/en_gum-ud-test.conllu",
	"Erzya": "UD_data/UD_Erzya-JR/myv_jr-ud-test.conllu",
	"Esperanto": "UD_data/UD_Esperanto-Prago/eo_prago-ud-test.conllu",
	"Estonian": "UD_data/UD_Estonian-EDT/et_edt-ud-test.conllu",
	"Faroese": "UD_data/UD_Faroese-FarPaHC/fo_farpahc-ud-test.conllu",
	"Finnish": "UD_data/UD_Finnish-TDT/fi_tdt-ud-test.conllu",
	"French": "UD_data/UD_French-GSD/fr_gsd-ud-test.conllu",
	"Frisian Dutch": "UD_data/UD_Frisian_Dutch-Fame/qfn_fame-ud-test.conllu",
	"Galician": "UD_data/UD_Galician-TreeGal/gl_treegal-ud-test.conllu",
	"Georgian": "UD_data/UD_Georgian-GLC/ka_glc-ud-test.conllu",
	"German": "UD_data/UD_German-HDT/de_hdt-ud-test.conllu",
	"Gheg": "UD_data/UD_Gheg-GPS/aln_gps-ud-test.conllu",
	"Gothic": "UD_data/UD_Gothic-PROIEL/got_proiel-ud-test.conllu",
	"Greek": "UD_data/UD_Greek-GUD/el_gud-ud-test.conllu",
	"Guajajara": "UD_data/UD_Guajajara-TuDeT/gub_tudet-ud-test.conllu",
	"Guarani": "UD_data/UD_Guarani-OldTuDeT/gn_oldtudet-ud-test.conllu",
	"Gujarati": "UD_data/UD_Gujarati-GujTB/gu_gujtb-ud-test.conllu",
	"Gwichin": "UD_data/UD_Gwichin-TueCL/gwi_tuecl-ud-test.conllu",
	"Haitian Creole": "UD_data/UD_Haitian_Creole-Adolphe/ht_adolphe-ud-test.conllu",
	"Hausa": "UD_data/UD_Hausa-SouthernAutogramm/ha_southernautogramm-ud-test.conllu",
	"Hebrew": "UD_data/UD_Hebrew-IAHLTwiki/he_iahltwiki-ud-test.conllu",
	"Highland P. Nahuatl": "UD_data/UD_Highland_Puebla_Nahuatl-ITML/azz_itml-ud-test.conllu",
	"Hindi": "UD_data/UD_Hindi-PUD/hi_pud-ud-test.conllu",
	"Hittite": "UD_data/UD_Hittite-HitTB/hit_hittb-ud-test.conllu",
	"Hungarian": "UD_data/UD_Hungarian-Szeged/hu_szeged-ud-test.conllu",
	"Icelandic": "UD_data/UD_Icelandic-IcePaHC/is_icepahc-ud-test.conllu",
	"Ika": "UD_data/UD_Ika-ChibErgIS/arh_chibergis-ud-test.conllu",
	"Indonesian": "UD_data/UD_Indonesian-PUD/id_pud-ud-test.conllu",
	"Irish": "UD_data/UD_Irish-IDT/ga_idt-ud-test.conllu",
	"Italian": "UD_data/UD_Italian-ISDT/it_isdt-ud-test.conllu",
	"Japanese": "UD_data/UD_Japanese-GSD/ja_gsd-ud-test.conllu",
	"Javanese": "UD_data/UD_Javanese-CSUI/jv_csui-ud-test.conllu",
	"Kaapor": "UD_data/UD_Kaapor-TuDeT/urb_tudet-ud-test.conllu",
	"Kangri": "UD_data/UD_Kangri-KDTB/xnr_kdtb-ud-test.conllu",
	"Karelian": "UD_data/UD_Karelian-KKPP/krl_kkpp-ud-test.conllu",
	"Karo": "UD_data/UD_Karo-TuDeT/arr_tudet-ud-test.conllu",
	"Kazakh": "UD_data/UD_Kazakh-KTB/kk_ktb-ud-test.conllu",
	"Khoekhoe": "UD_data/UD_Khoekhoe-KDT/naq_kdt-ud-test.conllu",
	"Khunsari": "UD_data/UD_Khunsari-AHA/kfm_aha-ud-test.conllu",
	"Kiche": "UD_data/UD_Kiche-IU/quc_iu-ud-test.conllu",
	"Komi Permyak": "UD_data/UD_Komi_Permyak-UH/koi_uh-ud-test.conllu",
	"Komi Zyrian": "UD_data/UD_Komi_Zyrian-Lattice/kpv_lattice-ud-test.conllu",
	"Korean": "UD_data/UD_Korean-Kaist/ko_kaist-ud-test.conllu",
	"Kurmanji": "UD_data/UD_Kurmanji-MG/kmr_mg-ud-test.conllu",
	"Kyrgyz": "UD_data/UD_Kyrgyz-KTMU/ky_ktmu-ud-test.conllu",
	"Latgalian": "UD_data/UD_Latgalian-Cairo/ltg_cairo-ud-test.conllu",
	"Latin": "UD_data/UD_Latin-ITTB/la_ittb-ud-test.conllu",
	"Latvian": "UD_data/UD_Latvian-LVTB/lv_lvtb-ud-test.conllu",
	"Ligurian": "UD_data/UD_Ligurian-GLT/lij_glt-ud-test.conllu",
	"Lithuanian": "UD_data/UD_Lithuanian-ALKSNIS/lt_alksnis-ud-test.conllu",
	"Livvi": "UD_data/UD_Livvi-KKPP/olo_kkpp-ud-test.conllu",
	"Low Saxon": "UD_data/UD_Low_Saxon-LSDC/nds_lsdc-ud-test.conllu",
	"Luxembourgish": "UD_data/UD_Luxembourgish-LuxBank/lb_luxbank-ud-test.conllu",
	"Macedonian": "UD_data/UD_Macedonian-MTB/mk_mtb-ud-test.conllu",
	"Madi": "UD_data/UD_Madi-Jarawara/jaa_jarawara-ud-test.conllu",
	"Maghrebi Arabic French": "UD_data/UD_Maghrebi_Arabic_French-Arabizi/qaf_arabizi-ud-test.conllu",
	"Makurap": "UD_data/UD_Makurap-TuDeT/mpu_tudet-ud-test.conllu",
	"Malayalam": "UD_data/UD_Malayalam-UFAL/ml_ufal-ud-test.conllu",
	"Maltese": "UD_data/UD_Maltese-MUDT/mt_mudt-ud-test.conllu",
	"Manx": "UD_data/UD_Manx-Cadhan/gv_cadhan-ud-test.conllu",
	"Marathi": "UD_data/UD_Marathi-UFAL/mr_ufal-ud-test.conllu",
	"Mbya Guarani": "UD_data/UD_Mbya_Guarani-Dooley/gun_dooley-ud-test.conllu",
	"Middle French": "UD_data/UD_Middle_French-PROFITEROLE/frm_profiterole-ud-test.conllu",
	"Moksha": "UD_data/UD_Moksha-JR/mdf_jr-ud-test.conllu",
	"Munduruku": "UD_data/UD_Munduruku-TuDeT/myu_tudet-ud-test.conllu",
	"Naga": "UD_data/UD_Naga-Suansu/nmf_suansu-ud-test.conllu",
	"Naija": "UD_data/UD_Naija-NSC/pcm_nsc-ud-test.conllu",
	"Nayini": "UD_data/UD_Nayini-AHA/nyq_aha-ud-test.conllu",
	"Neapolitan": "UD_data/UD_Neapolitan-RB/nap_rb-ud-test.conllu",
	"Nenets": "UD_data/UD_Nenets-Tundra/yrk_tundra-ud-test.conllu",
	"Nheengatu": "UD_data/UD_Nheengatu-CompLin/yrl_complin-ud-test.conllu",
	"North Sami": "UD_data/UD_North_Sami-Giella/sme_giella-ud-test.conllu",
	"Northwest Gbaya": "UD_data/UD_Northwest_Gbaya-Autogramm/gya_autogramm-ud-test.conllu",
	"Norwegian": "UD_data/UD_Norwegian-Bokmaal/no_bokmaal-ud-test.conllu",
	"Occitan": "UD_data/UD_Occitan-TTB/oc_ttb-ud-test.conllu",
	"Odia": "UD_data/UD_Odia-ODTB/or_odtb-ud-test.conllu",
	"Old Church Slavonic": "UD_data/UD_Old_Church_Slavonic-PROIEL/cu_proiel-ud-test.conllu",
	"Old East Slavic": "UD_data/UD_Old_East_Slavic-RNC/orv_rnc-ud-test.conllu",
	"Old English": "UD_data/UD_Old_English-Cairo/ang_cairo-ud-test.conllu",
	"Old French": "UD_data/UD_Old_French-PROFITEROLE/fro_profiterole-ud-test.conllu",
	"Old Irish": "UD_data/UD_Old_Irish-DipWBG/sga_dipwbg-ud-test.conllu",
	"Old Turkish": "UD_data/UD_Old_Turkish-Clausal/otk_clausal-ud-test.conllu",
	"Ottoman Turkish": "UD_data/UD_Ottoman_Turkish-DUDU/ota_dudu-ud-test.conllu",
	"Pashto": "UD_data/UD_Pashto-Sikaram/ps_sikaram-ud-test.conllu",
	"Paumari": "UD_data/UD_Paumari-TueCL/pad_tuecl-ud-test.conllu",
	"Persian": "UD_data/UD_Persian-PerDT/fa_perdt-ud-test.conllu",
	"Pesh": "UD_data/UD_Pesh-ChibErgIS/pay_chibergis-ud-test.conllu",
	"Phrygian": "UD_data/UD_Phrygian-KUL/xpg_kul-ud-test.conllu",
	"Polish": "UD_data/UD_Polish-PDB/pl_pdb-ud-test.conllu",
	"Pomak": "UD_data/UD_Pomak-Philotis/qpm_philotis-ud-test.conllu",
	"Portuguese": "UD_data/UD_Portuguese-Porttinari/pt_porttinari-ud-test.conllu",
	"Romanian": "UD_data/UD_Romanian-RRT/ro_rrt-ud-test.conllu",
	"Russian": "UD_data/UD_Russian-SynTagRus/ru_syntagrus-ud-test.conllu",
	"Sanskrit": "UD_data/UD_Sanskrit-Vedic/sa_vedic-ud-test.conllu",
	"Scottish Gaelic": "UD_data/UD_Scottish_Gaelic-ARCOSG/gd_arcosg-ud-test.conllu",
	"Serbian": "UD_data/UD_Serbian-SET/sr_set-ud-test.conllu",
	"Sindhi": "UD_data/UD_Sindhi-Isra/sd_isra-ud-test.conllu",
	"Sinhala": "UD_data/UD_Sinhala-STB/si_stb-ud-test.conllu",
	"Skolt Sami": "UD_data/UD_Skolt_Sami-Giellagas/sms_giellagas-ud-test.conllu",
	"Slovak": "UD_data/UD_Slovak-SNK/sk_snk-ud-test.conllu",
	"Slovenian": "UD_data/UD_Slovenian-SSJ/sl_ssj-ud-test.conllu",
	"Soi": "UD_data/UD_Soi-AHA/soj_aha-ud-test.conllu",
	"South Levantine Arabic": "UD_data/UD_South_Levantine_Arabic-MADAR/ajp_madar-ud-test.conllu",
	"Spanish": "UD_data/UD_Spanish-AnCora/es_ancora-ud-test.conllu",
	"Spanish Sign Language": "UD_data/UD_Spanish_Sign_Language-LSE/ssp_lse-ud-test.conllu",
	"Swedish": "UD_data/UD_Swedish-Talbanken/sv_talbanken-ud-test.conllu",
	"Swedish Sign Language": "UD_data/UD_Swedish_Sign_Language-SSLC/swl_sslc-ud-test.conllu",
	"Tagalog": "UD_data/UD_Tagalog-TRG/tl_trg-ud-test.conllu",
	"Tamil": "UD_data/UD_Tamil-TTB/ta_ttb-ud-test.conllu",
	"Tatar": "UD_data/UD_Tatar-NMCTT/tt_nmctt-ud-test.conllu",
	"Teko": "UD_data/UD_Teko-TuDeT/eme_tudet-ud-test.conllu",
	"Telugu": "UD_data/UD_Telugu-MTG/te_mtg-ud-test.conllu",
	"Telugu English": "UD_data/UD_Telugu_English-TECT/qte_tect-ud-test.conllu",
	"Thai": "UD_data/UD_Thai-PUD/th_pud-ud-test.conllu",
	"Tswana": "UD_data/UD_Tswana-Popapolelo/tn_popapolelo-ud-test.conllu",
	"Tupinamba": "UD_data/UD_Tupinamba-TuDeT/tpn_tudet-ud-test.conllu",
	"Turkish": "UD_data/UD_Turkish-Atis/tr_atis-ud-test.conllu",
	"Turkish English": "UD_data/UD_Turkish_English-BUTR/qti_butr-ud-test.conllu",
	"Turkish German": "UD_data/UD_Turkish_German-SAGT/qtd_sagt-ud-test.conllu",
	"Ukrainian": "UD_data/UD_Ukrainian-IU/uk_iu-ud-test.conllu",
	"Umbrian": "UD_data/UD_Umbrian-IKUVINA/xum_ikuvina-ud-test.conllu",
	"Upper Sorbian": "UD_data/UD_Upper_Sorbian-UFAL/hsb_ufal-ud-test.conllu",
	"Urdu": "UD_data/UD_Urdu-UDTB/ur_udtb-ud-test.conllu",
	"Uyghur": "UD_data/UD_Uyghur-UDT/ug_udt-ud-test.conllu",
	"Uzbek": "UD_data/UD_Uzbek-UT/uz_ut-ud-test.conllu",
	"Veps": "UD_data/UD_Veps-VWT/vep_vwt-ud-test.conllu",
	"Vietnamese": "UD_data/UD_Vietnamese-VTB/vi_vtb-ud-test.conllu",
	"Warlpiri": "UD_data/UD_Warlpiri-UFAL/wbp_ufal-ud-test.conllu",
	"Welsh": "UD_data/UD_Welsh-CCG/cy_ccg-ud-test.conllu",
	"Western Armenian": "UD_data/UD_Western_Armenian-ArmTDP/hyw_armtdp-ud-test.conllu",
	"Western S.P. Nahuatl": "UD_data/UD_Western_Sierra_Puebla_Nahuatl-ITML/nhi_itml-ud-test.conllu",
	"Wolof": "UD_data/UD_Wolof-WTB/wo_wtb-ud-test.conllu",
	"Xavante": "UD_data/UD_Xavante-XDT/xav_xdt-ud-test.conllu",
	"Xibe": "UD_data/UD_Xibe-XDT/sjo_xdt-ud-test.conllu",
	"Yakut": "UD_data/UD_Yakut-YKTDT/sah_yktdt-ud-test.conllu",
	"Yoruba": "UD_data/UD_Yoruba-YTB/yo_ytb-ud-test.conllu",
	"Yupik": "UD_data/UD_Yupik-SLI/ess_sli-ud-test.conllu"
}